function [ plotNames, titleInfo, legendInfo ] = loadSlideInfo( slideNum, ptype )
%LOADSLIDEINFO Load slide info for plotting.
%   Load slide info for plotting.

if ptype == 1
    if slideNum == 0 % Baselines
        plotNames = {};
        titleInfo = ['Baseline Training Results in Pybullet for Pendulum'];
        legendInfo = {'baseline_{raw}', 'baseline_{ema}'};
    elseif slideNum == 1 % Naive transfer of weights
        plotNames = {'014'};
        titleInfo = ['Naive Transfer of Weights'];
        legendInfo = {'vanilla_{raw}', 'vanilla_{ema}', ...
                      'baseline_{raw}', 'baseline_{ema}'};
    elseif slideNum == 2 % Naive transfer to realistic joints
        plotNames = {'014', '008', '010'};
        titleInfo = ['Naive Transfer to Target with Realistic Joints'];
        legendInfo = {'vanilla_{raw}', 'vanilla_{ema}', ...
                      'van-Dmp_{raw}', 'van-Dmp_{ema}', ...
                      'van-Frc_{raw}', 'van-Frc_{ema}', ...
                      'baseline_{raw}', 'baseline_{ema}'};
    elseif slideNum == 3
        plotNames = {'014', '003', '004', '015'};
        titleInfo = ['Transfer Target with Different Inertial Parameters'];
        legendInfo = {'vanilla_{raw}', 'vanilla_{ema}', ...
                      'van-IU_{raw}', 'van-IU_{ema}', ...
                      'van-IU-Dmp_{raw}', 'van-IU-Dmp_{ema}', ...
                      'van-IU-Frc_{raw}', 'van-IU-Frc_{ema}', ...
                      'baseline_{raw}', 'baseline_{ema}'};
    elseif slideNum == 4
        plotNames = {'003', '017', '005', '016'};
        titleInfo = ['Moderate DR Source to IU Target'];
        legendInfo = {'van-tIU_{raw}', 'van-tIU_{ema}', ...
                      'sMDR-tIU_{raw}', 'sMDR-tIU_{ema}', ...
                      'sMDR-tIU-Dmp_{raw}', 'sMDR-tIU-Dmp_{ema}', ...
                      'sMDR-tIU-Frc_{raw}', 'sMDR-tIU-Frc_{ema}', ...
                      'baseline_{raw}', 'baseline_{ema}'};
    elseif slideNum == 5
        plotNames = {'003', '024', '023', '025'};
        titleInfo = ['Bigger DR Source to IU Target'];
        legendInfo = {'van-tIU_{raw}', 'van-tIU_{ema}', ...
                      'sBDR-tIU_{raw}', 'sBDR-tIU_{ema}', ...
                      'sBDR-tIU-Dmp_{raw}', 'sBDR-tIU-Dmp_{ema}', ...
                      'sBDR-tIU-Frc_{raw}', 'sBDR-tIU-Frc_{ema}', ...
                      'baseline_{raw}', 'baseline_{ema}'};
    elseif slideNum == 6
        plotNames = {'024', '026', '027'};
        titleInfo = ['Learning Rates Effect'];
        legendInfo = {'sBDR-tIU_{raw}', 'sBDR-tIU_{ema}', ...
                      'sBDR-tIU-1_{raw}', 'sBDR-tIU-1_{ema}', ...
                      'sBDR-tIU-2_{raw}', 'sBDR-tIU-2_{ema}', ...
                      'baseline_{raw}', 'baseline_{ema}'};
    elseif slideNum == 7
        plotNames = {'026', '028'};
        titleInfo = ['Arbitrary DR vs EDR'];
        legendInfo = {'sBDR-tIU-1_{raw}', 'sBDR-tIU-1_{ema}', ...
                      'sEDR-tIU_{raw}', 'sEDR-tIU_{ema}', ...
                      'baseline_{raw}', 'baseline_{ema}'};
    elseif slideNum == 99
        plotNames = {'014', '008', '010', ...
                     '003', '004', '015', ...
                     '017', '005', '016', ...
                     '024', '023', '025', ...
                     '026', '027'};
        titleInfo = ['All Test Cases Overlayed (Pendulum)'];
        legendInfo = {'van2van_{raw}', 'van2van_{ema}', ...
                      'van2dmp_{raw}', 'van2dmp_{ema}', ...
                      'van2frc_{raw}', 'van2frc_{ema}', ...
                      'van2iu_{raw}', 'van2iu_{ema}', ...
                      'van2iu-dmp_{raw}', 'van2iu-dmp_{ema}', ...
                      'van2iu-frc_{raw}', 'van2iu-frc_{ema}', ...
                      'sdr2iu_{raw}', 'sdr2iu_{ema}', ...
                      'sdr2iu-dmp_{raw}', 'sdr2iu-dmp_{ema}', ...
                      'sdr2iu-frc_{raw}', 'sdr2iu-frc_{ema}', ...
                      'bdr2iu_{raw}', 'bdr2iu_{ema}', ...
                      'bdr2iu-dmp_{raw}', 'bdr2iu-dmp_{ema}', ...
                      'bdr2iu-frc_{raw}', 'bdr2iu-frc_{ema}', ...
                      'bdr2iu-lr\_low_{raw}', 'bdr2iu-lr\_low_{ema}', ...
                      'bdr2iu-lr\_high_{raw}', 'bdr2iu-lr\_high_{ema}', ...
                      'baseline_{raw}', 'baseline_{ema}'};
    end
elseif ptype == 2
    if slideNum == 0
        plotNames = {};
        titleInfo = ['Baseline Training Results in Pybullet for Cart Pole'];
        legendInfo = {'baseline_{raw}', 'baseline_{ema}'};
    elseif slideNum == 1
        plotNames = {'001'};
        titleInfo = ['Naive Transfer of Weights'];
        legendInfo = {'vanilla_{raw}', 'vanilla_{ema}', ...
                      'baseline_{raw}', 'baseline_{ema}'};
    elseif slideNum == 2
        plotNames = {'001', '002', '003'};
        titleInfo = ['Naive Transfer to Target with Realistic Joints'];
        legendInfo = {'vanilla_{raw}', 'vanilla_{ema}', ...
                      'van-Dmp_{raw}', 'van-Dmp_{ema}', ...
                      'van-Frc_{raw}', 'van-Frc_{ema}', ...
                      'baseline_{raw}', 'baseline_{ema}'};
    elseif slideNum == 3
        plotNames = {'001', '004', '005', '006'};
        titleInfo = ['Transfer Target with Different Inertial Parameters'];
        legendInfo = {'vanilla_{raw}', 'vanilla_{ema}', ...
                      'van-IU_{raw}', 'van-IU_{ema}', ...
                      'van-IU-Dmp_{raw}', 'van-IU-Dmp_{ema}', ...
                      'van-IU-Frc_{raw}', 'van-IU-Frc_{ema}', ...
                      'baseline_{raw}', 'baseline_{ema}'};
    elseif slideNum == 4
        plotNames = {'004', '007', '008', '009'};
        titleInfo = ['Moderate DR Source to IU Target'];
        legendInfo = {'van-tIU_{raw}', 'van-tIU_{ema}', ...
                      'sMDR-tIU_{raw}', 'sMDR-tIU_{ema}', ...
                      'sMDR-tIU-Dmp_{raw}', 'sMDR-tIU-Dmp_{ema}', ...
                      'sMDR-tIU-Frc_{raw}', 'sMDR-tIU-Frc_{ema}', ...
                      'baseline_{raw}', 'baseline_{ema}'};
    elseif slideNum == 5
        plotNames = {'004', '010', '011', '012'};
        titleInfo = ['Bigger DR Source to IU Target'];
        legendInfo = {'van-tIU_{raw}', 'van-tIU_{ema}', ...
                      'sBDR-tIU_{raw}', 'sBDR-tIU_{ema}', ...
                      'sBDR-tIU-Dmp_{raw}', 'sBDR-tIU-Dmp_{ema}', ...
                      'sBDR-tIU-Frc_{raw}', 'sBDR-tIU-Frc_{ema}', ...
                      'baseline_{raw}', 'baseline_{ema}'};
    elseif slideNum == 6
        plotNames = {'010', '013', '014'};
        titleInfo = ['Learning Rates Effect'];
        legendInfo = {'sBDR-tIU_{raw}', 'sBDR-tIU_{ema}', ...
                      'sBDR-tIU-1_{raw}', 'sBDR-tIU-1_{ema}', ...
                      'sBDR-tIU-2_{raw}', 'sBDR-tIU-2_{ema}', ...
                      'baseline_{raw}', 'baseline_{ema}'};
    elseif slideNum == 99
        plotNames = {'001', '002', '003', ...
                     '004', '005', '006', ...
                     '007', '008', '009', ...
                     '010', '011', '012', ...
                     '013', '014'};
        titleInfo = ['All Test Cases Overlayed (Cart Pole)'];
        legendInfo = {'van2van_{raw}', 'van2van_{ema}', ...
                      'van2dmp_{raw}', 'van2dmp_{ema}', ...
                      'van2frc_{raw}', 'van2frc_{ema}', ...
                      'van2iu_{raw}', 'van2iu_{ema}', ...
                      'van2iu-dmp_{raw}', 'van2iu-dmp_{ema}', ...
                      'van2iu-frc_{raw}', 'van2iu-frc_{ema}', ...
                      'sdr2iu_{raw}', 'sdr2iu_{ema}', ...
                      'sdr2iu-dmp_{raw}', 'sdr2iu-dmp_{ema}', ...
                      'sdr2iu-frc_{raw}', 'sdr2iu-frc_{ema}', ...
                      'bdr2iu_{raw}', 'bdr2iu_{ema}', ...
                      'bdr2iu-dmp_{raw}', 'bdr2iu-dmp_{ema}', ...
                      'bdr2iu-frc_{raw}', 'bdr2iu-frc_{ema}', ...
                      'bdr2iu-lr\_low_{raw}', 'bdr2iu-lr\_low_{ema}', ...
                      'bdr2iu-lr\_high_{raw}', 'bdr2iu-lr\_high_{ema}', ...
                      'baseline_{raw}', 'baseline_{ema}'};
    end
elseif ptype == 3
    if slideNum == 1
        plotNames = {'002', '001'};
        titleInfo = ['Regular DR vs. EDR'];
        legendInfo = {'edr_{raw}', 'edr_{ema}', ...
                      'bdr_{raw}', 'bdr_{ema}'};
    end
end

end

